### Importación de librerías

In [1]:
#Libraria numpy
import numpy as np #Incuye funciones de array

### Algoritmo

In [143]:
def sorter(data):
    #Muestreo del array introducido
    print("Array introducido: ", data, "\n")
    #Copiar datos
    sortdata=data.copy()
    #Logitud
    datashape=data.shape[0]
    #Comienzo de la organización de elemento por el segundo elemento
    for i in range(1,datashape):
        #valor de la posición de evalución copiada en variable auxiliar
        aux=sortdata[i]
        #C queda definida por el valor de i
        c=i
        counter=0
        #Evaluación de la posición del array con todas las anteriores
        for j in range(1,i+1):     
            #El valor actual evaluado debe ser mayor al anterior
            #En caso de que asi no se de en los datos de entrada cambiará su posición 
            #con la posición que guarda un menor valor en el array
            if (sortdata[c]<sortdata[i-j]):
                counter=counter+1
                if counter==1:
                    print ("Valor", sortdata[c], "en la posición", c+1, "desordenado. Procedemos a ordenarlo.")
                print(sortdata[c], "cambia su posición con", sortdata[i-j] )
                sortdata[c]=sortdata[c-1]
                sortdata[c-1]=aux
                c=i-j
                print(sortdata,  "\n")
    #Sort array            
    return sortdata
    

## Datos introducidos y llamada a la función

In [148]:
data=np.random.randint(100, size=5)
print( "Datos ordenados: ", sorter(data))

Array introducido:  [67 51 28  0 99] 

Valor 51 en la posición 2 desordenado. Procedemos a ordenarlo.
51 cambia su posición con 67
[51 67 28  0 99] 

Valor 28 en la posición 3 desordenado. Procedemos a ordenarlo.
28 cambia su posición con 67
[51 28 67  0 99] 

28 cambia su posición con 51
[28 51 67  0 99] 

Valor 0 en la posición 4 desordenado. Procedemos a ordenarlo.
0 cambia su posición con 67
[28 51  0 67 99] 

0 cambia su posición con 51
[28  0 51 67 99] 

0 cambia su posición con 28
[ 0 28 51 67 99] 

Datos ordenados:  [ 0 28 51 67 99]
